type=DINPUT
name=RPG
AXIS_GSENSOR=STICK_RIGHT
AXIS_DPAD=STICK_LEFT
HW_KEY_A=BTN_A
HW_KEY_B=BTN_X
HW_KEY_START=BTN_RIGHT_THUMB
HW_KEY_SELECT=BTN_LEFT_THUMB
HW_KEY_L3=BTN_FN
FKEY_HW_KEY_A=BTN_B
FKEY_HW_KEY_B=BTN_Y
FKEY_HW_KEY_START=BTN_RB
FKEY_HW_KEY_SELECT=BTN_LB

