type=DIRECT
name=CatMario
HW_KEY_UP=HID_KEY_ESC
HW_KEY_DOWN=HID_KEY_DOWN
HW_KEY_LEFT=HID_KEY_LEFT
HW_KEY_RIGHT=HID_KEY_RIGHT
HW_KEY_A=HID_KEY_UP
HW_KEY_B=HID_KEY_F1
HW_KEY_START=HID_KEY_ENTER
HW_KEY_SELECT=HID_KEY_O
HW_KEY_L3=HID_KEY_SPACE
